# Generated by Django 2.2.7 on 2019-11-04 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.IntegerField()),
                ('pais', models.CharField(max_length=30)),
                ('demarcacion', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('pierna_buena', models.CharField(max_length=30)),
                ('estatura', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateField()),
                ('resultado', models.CharField(max_length=30)),
                ('marcador', models.CharField(max_length=30)),
                ('competicion', models.CharField(max_length=30)),
                ('instancia', models.CharField(max_length=50)),
                ('temporada', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alineacion', models.CharField(max_length=30)),
                ('minutos_jugados', models.IntegerField()),
                ('temporada', models.CharField(max_length=10)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('temporada', models.CharField(max_length=10)),
                ('anotador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Partido')),
            ],
        ),
    ]
